"""added new field

Revision ID: da886d1119c5
Revises: 348bfeb0a354
Create Date: 2023-03-02 16:50:01.783376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da886d1119c5'
down_revision = '348bfeb0a354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
